import { jsPDF } from 'jspdf';
import { MODEL_META } from './Modelmeta';

/* ------------------------------------------------------------------ */
/* Report generation — compiles a whole session into one audit-format */
/* PDF. Vector text throughout (not a screenshot), so it stays sharp  */
/* and searchable/selectable at any zoom, which matters for a         */
/* document meant to be submitted rather than just viewed on screen.  */
/* ------------------------------------------------------------------ */

const PAGE = { width: 210, height: 297 }; // A4, mm
const MARGIN = 18;
const CONTENT_WIDTH = PAGE.width - MARGIN * 2;
const GOLD = [212, 168, 67];
const GOLD_DEEP = [148, 108, 22]; // darker gold, readable as text on white
const INK = [22, 22, 26];
const BODY = [55, 55, 60];
const MUTED = [125, 125, 132];
const RULE = [225, 225, 228];

function blobUrlToDataUrl(url) {
  return fetch(url)
    .then((res) => res.blob())
    .then(
      (blob) =>
        new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result);
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        })
    );
}

function loadImageDims(dataUrl) {
  return new Promise((resolve) => {
    const img = new window.Image();
    img.onload = () => resolve({ width: img.naturalWidth || 1, height: img.naturalHeight || 1 });
    img.onerror = () => resolve({ width: 1, height: 1 });
    img.src = dataUrl;
  });
}

function drawLogoMark(doc, cx, cy, r) {
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.circle(cx, cy, r, 'S');
  doc.line(cx, cy - r - 1.6, cx, cy - r + 1.6);
  doc.line(cx, cy + r - 1.6, cx, cy + r + 1.6);
  doc.line(cx - r - 1.6, cy, cx - r + 1.6, cy);
  doc.line(cx + r - 1.6, cy, cx + r + 1.6, cy);
}

function drawPageHeader(doc) {
  drawLogoMark(doc, MARGIN + 3, 14, 3);
  doc.setFont('courier', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...INK);
  doc.text('SKYLENS', MARGIN + 9, 15.5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text('GEOSPATIAL ANALYSIS REPORT', PAGE.width - MARGIN, 15.5, { align: 'right' });

  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, 20, PAGE.width - MARGIN, 20);
}

function drawPageFooter(doc, pageNum, totalPages, refId) {
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE.height - 16, PAGE.width - MARGIN, PAGE.height - 16);

  doc.setFont('courier', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(`REF ${refId}`, MARGIN, PAGE.height - 10);
  doc.text(
    'CONFIDENTIAL \u2014 SYSTEM-GENERATED, SUBJECT TO SECOND-PASS REVIEW',
    PAGE.width / 2,
    PAGE.height - 10,
    { align: 'center' }
  );
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.width - MARGIN, PAGE.height - 10, {
    align: 'right',
  });
}

export async function generateSessionReport(session, generatedBy) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const refId = `SQ-${session.id.split('-').slice(-1)[0].toUpperCase()}`;
  const generatedAt = new Date();
  let y = 32;

  const ensureSpace = (needed) => {
    if (y + needed > PAGE.height - MARGIN - 10) {
      doc.addPage();
      y = 32;
    }
  };

  drawPageHeader(doc);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(...INK);
  const titleLines = doc.splitTextToSize(
    session.title === 'New session' ? 'Untitled session' : session.title,
    CONTENT_WIDTH
  );
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 7 + 4;

  const userTurns = session.messages.filter((m) => m.role === 'user').length;
  const agentTurns = session.messages.filter((m) => m.role === 'agent');
  const agentTurnsWithConfidence = agentTurns.filter((m) => m.confidence !== undefined && m.confidence !== null);
  const avgConfidence = agentTurnsWithConfidence.length
    ? Math.round(agentTurnsWithConfidence.reduce((sum, m) => sum + m.confidence, 0) / agentTurnsWithConfidence.length)
    : null;

  const meta = [
    ['Report reference', refId],
    ['Queries submitted', String(userTurns)],
    ['AI responses', String(agentTurns.length)],
    ['Average confidence', avgConfidence !== null ? `${avgConfidence}%` : '\u2014'],
    ['Generated by', generatedBy || 'Unknown user'],
    ['Generated', generatedAt.toLocaleString()],
  ];
  doc.setFontSize(9);
  meta.forEach(([label, value], i) => {
    const rowY = y + i * 5.5;
    doc.setFont('courier', 'normal');
    doc.setTextColor(...MUTED);
    doc.text(label.toUpperCase(), MARGIN, rowY);
    doc.setFont('courier', 'bold');
    doc.setTextColor(...GOLD_DEEP);
    doc.text(value, MARGIN + 55, rowY);
  });
  y += meta.length * 5.5 + 6;

  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE.width - MARGIN, y);
  y += 9;

  let qIndex = 0;
  for (let i = 0; i < session.messages.length; i++) {
    const m = session.messages[i];
    if (m.role !== 'user') continue;
    qIndex += 1;
    const reply = session.messages[i + 1]?.role === 'agent' ? session.messages[i + 1] : null;

    ensureSpace(16);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11.5);
    doc.setTextColor(...INK);
    doc.text(`Query ${qIndex}`, MARGIN, y);
    y += 6;

    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9.5);
    doc.setTextColor(...BODY);
    const queryLines = doc.splitTextToSize(`\u201c${m.text}\u201d`, CONTENT_WIDTH);
    ensureSpace(queryLines.length * 5);
    doc.text(queryLines, MARGIN, y);
    y += queryLines.length * 5 + 4;

    if (!reply) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...MUTED);
      ensureSpace(6);
      doc.text('No response recorded for this query.', MARGIN, y);
      y += 10;
      continue;
    }

    // Special handling for Model 2 (Change Detection)
    if (reply.model === 'bitcd') {
      // Display Before/After images with labels
      if (reply.images?.length >= 2) {
        const box = 42;
        ensureSpace(box + 12);
        const gap = 8;
        const totalWidth = box * 2 + gap;
        const startX = MARGIN + (CONTENT_WIDTH - totalWidth) / 2;
        
        // Before image
        try {
          const dataUrl = await blobUrlToDataUrl(reply.images[0].url);
          const dims = await loadImageDims(dataUrl);
          const scale = Math.min(box / dims.width, box / dims.height);
          const w = dims.width * scale;
          const h = dims.height * scale;
          doc.setDrawColor(...GOLD);
          doc.setLineWidth(0.5);
          doc.rect(startX, y, box, box);
          doc.addImage(dataUrl, startX + (box - w) / 2, y + (box - h) / 2, w, h);
          doc.setFont('courier', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(...GOLD_DEEP);
          doc.text('BEFORE', startX + box / 2, y + box + 5, { align: 'center' });
        } catch (e) {
          doc.setDrawColor(...RULE);
          doc.rect(startX, y, box, box);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.setTextColor(...MUTED);
          doc.text('Image unavailable', startX + box / 2, y + box / 2, { align: 'center' });
        }
        
        // After image
        try {
          const dataUrl = await blobUrlToDataUrl(reply.images[1].url);
          const dims = await loadImageDims(dataUrl);
          const scale = Math.min(box / dims.width, box / dims.height);
          const w = dims.width * scale;
          const h = dims.height * scale;
          doc.setDrawColor(...GOLD);
          doc.setLineWidth(0.5);
          doc.rect(startX + box + gap, y, box, box);
          doc.addImage(dataUrl, startX + box + gap + (box - w) / 2, y + (box - h) / 2, w, h);
          doc.setFont('courier', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(...GOLD_DEEP);
          doc.text('AFTER', startX + box + gap + box / 2, y + box + 5, { align: 'center' });
        } catch (e) {
          doc.setDrawColor(...RULE);
          doc.rect(startX + box + gap, y, box, box);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.setTextColor(...MUTED);
          doc.text('Image unavailable', startX + box + gap + box / 2, y + box / 2, { align: 'center' });
        }
        
        y += box + 10;
      }
      
      // Display change detection mask if available
      if (reply.changeMaskUrl) {
        ensureSpace(50);
        const maskBox = 45;
        const maskX = MARGIN + (CONTENT_WIDTH - maskBox) / 2;
        
        try {
          const dataUrl = reply.changeMaskUrl.startsWith('data:') 
            ? reply.changeMaskUrl 
            : await blobUrlToDataUrl(reply.changeMaskUrl);
          const dims = await loadImageDims(dataUrl);
          const scale = Math.min(maskBox / dims.width, maskBox / dims.height);
          const w = dims.width * scale;
          const h = dims.height * scale;
          
          doc.setDrawColor(...GOLD);
          doc.setLineWidth(0.5);
          doc.rect(maskX, y, maskBox, maskBox);
          doc.addImage(dataUrl, maskX + (maskBox - w) / 2, y + (maskBox - h) / 2, w, h);
          
          doc.setFont('courier', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(...GOLD_DEEP);
          doc.text('CHANGE DETECTION MASK', maskX + maskBox / 2, y + maskBox + 5, { align: 'center' });
          y += maskBox + 8;
        } catch (e) {
          console.error('Failed to load change mask:', e);
        }
      }
      
      // Display change detection metrics
      ensureSpace(12);
      const metricsX = MARGIN + (CONTENT_WIDTH - 100) / 2;
      doc.setFont('courier', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...INK);
      doc.text('CHANGE DETECTION', metricsX, y);
      y += 6;
      
      doc.setFont('courier', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...BODY);
      const changeDetected = reply.changePercent > 0 ? 'YES' : 'NO';
      doc.text(`CHANGE DETECTED: ${changeDetected}`, metricsX, y);
      y += 5;
      doc.text(`CHANGE AREA: ${reply.changePercent}%`, metricsX, y);
      y += 8;
      
      // Display explanation text
      ensureSpace(6);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...INK);
      const answerLines = doc.splitTextToSize(reply.text, CONTENT_WIDTH);
      ensureSpace(answerLines.length * 5);
      doc.text(answerLines, MARGIN, y);
      y += answerLines.length * 5 + 6;
      
      // Model info without confidence
      ensureSpace(7);
      doc.setFont('courier', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...GOLD_DEEP);
      doc.text(
        `${MODEL_META[reply.model].name}  \u00b7  ${reply.responseTime}s  \u00b7  SECOND REVIEW: PENDING`,
        MARGIN,
        y
      );
      y += 10;
      
      doc.setDrawColor(...RULE);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y - 4, PAGE.width - MARGIN, y - 4);
      continue;
    }

    // Special handling for Model 3 (Optical+SAR Fusion) — no imagery to
    // render, so the block leads with Primary Prediction / Confidence
    // Score as their own rows, then the full Top-5 ranked list.
    if (reply.model === 'fusion') {
      const primaryClass = reply.primaryClass || reply.fusionResults?.[0]?.label || 'Unknown';
      const primaryConfidence = reply.primaryConfidence ?? reply.confidence ?? 0;
      const top5 = reply.fusionResults || [];

      ensureSpace(14);
      const boxX = MARGIN;
      const boxW = CONTENT_WIDTH;

      // Primary Prediction row
      doc.setFont('courier', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text('PRIMARY PREDICTION', boxX, y);
      y += 5;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(...INK);
      const primaryLines = doc.splitTextToSize(primaryClass, boxW);
      ensureSpace(primaryLines.length * 5.5);
      doc.text(primaryLines, boxX, y);
      y += primaryLines.length * 5.5 + 5;

      // Confidence Score row
      ensureSpace(10);
      doc.setFont('courier', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text('CONFIDENCE SCORE', boxX, y);
      y += 5;
      doc.setFont('courier', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(...GOLD_DEEP);
      doc.text(`${primaryConfidence}%`, boxX, y);

      // Confidence bar next to the number
      const barX = boxX + 22;
      const barW = 60;
      const barY = y - 3.2;
      doc.setDrawColor(...RULE);
      doc.setLineWidth(2);
      doc.line(barX, barY, barX + barW, barY);
      doc.setDrawColor(...GOLD);
      doc.setLineWidth(2);
      doc.line(barX, barY, barX + (barW * Math.min(100, Math.max(0, primaryConfidence))) / 100, barY);
      y += 9;

      // Top-5 predictions table
      if (top5.length) {
        ensureSpace(top5.length * 5.5 + 12);
        doc.setFont('courier', 'bold');
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTED);
        doc.text('TOP 5 PREDICTIONS', boxX, y);
        y += 5;
        doc.setDrawColor(...RULE);
        doc.setLineWidth(0.2);
        doc.line(MARGIN, y, PAGE.width - MARGIN, y);
        y += 4.5;

        doc.setFont('courier', 'normal');
        doc.setFontSize(8.5);
        top5.forEach((f, idx) => {
          ensureSpace(6.5);
          const rowY = y;

          doc.setTextColor(...BODY);
          doc.text(`${idx + 1}.`, MARGIN, rowY);

          const labelLines = doc.splitTextToSize(f.label, CONTENT_WIDTH - 30);
          doc.text(labelLines[0], MARGIN + 7, rowY);

          doc.setFont('courier', 'bold');
          doc.setTextColor(idx === 0 ? GOLD_DEEP[0] : BODY[0], idx === 0 ? GOLD_DEEP[1] : BODY[1], idx === 0 ? GOLD_DEEP[2] : BODY[2]);
          doc.text(`${f.confidence}%`, PAGE.width - MARGIN, rowY, { align: 'right' });
          doc.setFont('courier', 'normal');

          // Small inline bar under the label, scaled to this class's confidence
          const miniBarX = MARGIN + 7;
          const miniBarW = 130;
          const miniBarY = rowY + 1.6;
          doc.setDrawColor(...RULE);
          doc.setLineWidth(1.2);
          doc.line(miniBarX, miniBarY, miniBarX + miniBarW, miniBarY);
          doc.setDrawColor(...GOLD);
          doc.setLineWidth(1.2);
          doc.line(miniBarX, miniBarY, miniBarX + (miniBarW * Math.min(100, Math.max(0, f.confidence))) / 100, miniBarY);

          y += 6.5;
        });
        y += 3;
      }

      // Location / date context, if present
      if (reply.location || reply.requestedDate) {
        ensureSpace(6);
        doc.setFont('courier', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTED);
        const lat = reply.location?.latitude ?? reply.location?.lat;
        const lon = reply.location?.longitude ?? reply.location?.lon;
        const contextParts = [];
        if (lat !== undefined && lon !== undefined) contextParts.push(`LAT ${lat} \u00b7 LON ${lon}`);
        if (reply.requestedDate) contextParts.push(`DATE ${reply.requestedDate}`);
        if (reply.sentinel1Date) contextParts.push(`SAR PASS ${reply.sentinel1Date}`);
        if (contextParts.length) {
          doc.text(contextParts.join('   \u00b7   '), MARGIN, y);
          y += 6;
        }
      }

      // Model info footer for this turn
      ensureSpace(7);
      doc.setFont('courier', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...GOLD_DEEP);
      doc.text(
        `${MODEL_META[reply.model].name}  \u00b7  ${reply.responseTime}s  \u00b7  SECOND REVIEW: PENDING`,
        MARGIN,
        y
      );
      y += 10;

      doc.setDrawColor(...RULE);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y - 4, PAGE.width - MARGIN, y - 4);
      continue;
    }

    // Standard format for other models
    if (reply.images?.length) {
      const box = 36;
      ensureSpace(box + 8);
      let x = MARGIN;
      for (const img of reply.images) {
        try {
          const dataUrl = await blobUrlToDataUrl(img.url);
          const dims = await loadImageDims(dataUrl);
          const scale = Math.min(box / dims.width, box / dims.height);
          const w = dims.width * scale;
          const h = dims.height * scale;
          doc.setDrawColor(...RULE);
          doc.setLineWidth(0.3);
          doc.rect(x, y, box, box);
          doc.addImage(dataUrl, x + (box - w) / 2, y + (box - h) / 2, w, h);
          if (img.date) {
            doc.setFont('courier', 'normal');
            doc.setFontSize(6.5);
            doc.setTextColor(...MUTED);
            doc.text(img.date, x + box / 2, y + box + 4, { align: 'center' });
          }
        } catch (e) {
          doc.setDrawColor(...RULE);
          doc.rect(x, y, box, box);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(7);
          doc.setTextColor(...MUTED);
          doc.text('Image unavailable', x + box / 2, y + box / 2, { align: 'center' });
        }
        x += box + 6;
      }
      y += box + 9;
    }

    ensureSpace(6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(...INK);
    const answerLines = doc.splitTextToSize(reply.text, CONTENT_WIDTH);
    ensureSpace(answerLines.length * 5);
    doc.text(answerLines, MARGIN, y);
    y += answerLines.length * 5 + 4;

    if (reply.evidence) {
      ensureSpace(8);
      doc.setFont('courier', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      const ev = doc.splitTextToSize(reply.evidence, CONTENT_WIDTH);
      doc.text(ev, MARGIN, y);
      y += ev.length * 4.2 + 3;
    }

    const rows = reply.detections
      ? reply.detections.map((d, idx) => [String(idx + 1), d.label, `${d.confidence}%`, `${d.area} km\u00b2`])
      : reply.changeRegions
      ? reply.changeRegions.map((r, idx) => [String(idx + 1), r.label, '\u2014', '\u2014'])
      : [];

    if (rows.length) {
      ensureSpace(rows.length * 5.5 + 10);
      const col = [MARGIN, MARGIN + 9, MARGIN + 118, MARGIN + 152];
      doc.setFont('courier', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text('#', col[0], y);
      doc.text('DETECTION', col[1], y);
      doc.text('CONFIDENCE', col[2], y);
      doc.text('AREA', col[3], y);
      y += 3;
      doc.setDrawColor(...RULE);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y, PAGE.width - MARGIN, y);
      y += 4.5;

      doc.setFont('courier', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(...BODY);
      rows.forEach((r) => {
        ensureSpace(5.5);
        doc.text(r[0], col[0], y);
        doc.text(r[1], col[1], y);
        doc.text(r[2], col[2], y);
        doc.text(r[3], col[3], y);
        y += 5.5;
      });
      y += 3;
    }

    ensureSpace(7);
    doc.setFont('courier', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(...GOLD_DEEP);
    doc.text(
      `${MODEL_META[reply.model].name}  \u00b7  CONFIDENCE ${reply.confidence}%  \u00b7  ${reply.responseTime}s  \u00b7  SECOND REVIEW: PENDING`,
      MARGIN,
      y
    );
    y += 10;

    doc.setDrawColor(...RULE);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y - 4, PAGE.width - MARGIN, y - 4);
  }

  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    if (p > 1) drawPageHeader(doc);
    drawPageFooter(doc, p, totalPages, refId);
  }

  return { doc, refId };
}